# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'buy_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(520, 330)
        Frame.setMinimumSize(QtCore.QSize(520, 330))
        Frame.setMaximumSize(QtCore.QSize(520, 330))
        Frame.setStyleSheet("font-size: 30px;\n"
"background-color: rgb(30, 35, 40);\n"
"color: white;\n"
"font-family: \"Mongolian Baiti\";\n"
"")
        self.pushButton = QtWidgets.QPushButton(Frame)
        self.pushButton.setGeometry(QtCore.QRect(270, 240, 241, 81))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton.setStyleSheet("QPushButton{\n"
"border-radius: 10px;\n"
"padding: 10px;\n"
"font-size: 20px;\n"
"color: black;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.227, x2:1, y2:0.739, stop:0 rgba(0, 255, 0, 255), stop:0.507389 rgba(0, 255, 255, 255), stop:1 rgba(0, 56, 255, 255));\n"
"border: 2px solid rgb(0,0,0,0);\n"
"}\n"
"QPushButton:hover{\n"
"border-color:  black;\n"
"    background-color: rgb(0, 255, 77);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Frame)
        self.pushButton_2.setGeometry(QtCore.QRect(110, 240, 151, 81))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"border-radius: 10px;\n"
"padding: 10px;\n"
"font-size: 20px;\n"
"color: white;\n"
"    background-color: rgb(200,200,200, 20);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border-color:  black;\n"
"    background-color: rgb(60,60,60);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(Frame)
        self.label.setGeometry(QtCore.QRect(0, 0, 521, 71))
        self.label.setStyleSheet("color: black;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.227, x2:1, y2:0.739, stop:0 rgba(0, 255, 0, 255), stop:0.507389 rgba(0, 255, 255, 255), stop:1 rgba(0, 56, 255, 255));")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.textBrowser = QtWidgets.QTextBrowser(Frame)
        self.textBrowser.setGeometry(QtCore.QRect(10, 80, 501, 141))
        self.textBrowser.setFocusPolicy(QtCore.Qt.NoFocus)
        self.textBrowser.setInputMethodHints(QtCore.Qt.ImhNone)
        self.textBrowser.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser.setReadOnly(False)
        self.textBrowser.setOpenLinks(False)
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton_2.raise_()
        self.label.raise_()
        self.pushButton.raise_()
        self.textBrowser.raise_()

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Xarid qilish"))
        self.pushButton.setText(_translate("Frame", "Sotib olish"))
        self.pushButton_2.setText(_translate("Frame", "Yo\'q"))
        self.label.setText(_translate("Frame", "Xarid qilishni istaysizmi?"))
        self.textBrowser.setHtml(_translate("Frame", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Mongolian Baiti\'; font-size:30px; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt;\">Miqdor: </span><span style=\" font-size:28pt; font-weight:600; color:#55ffff;\">3 oy</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt;\">Chegirma: </span><span style=\" font-size:28pt; font-weight:600; color:#ff0000;\">-20%</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt;\">Umumiy narx: </span><span style=\" font-size:28pt; font-weight:600; color:#00ff80;\">600 000</span><span style=\" font-size:28pt; font-weight:600;\"> so\'m</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())
