# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1206, 767)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/main-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("\n"
"background-color: rgb(27, 29, 36);\n"
"color: white;\n"
"font-family: \"Mongolian Baiti\";\n"
"")
        MainWindow.setIconSize(QtCore.QSize(24, 24))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setMinimumSize(QtCore.QSize(220, 0))
        self.frame_3.setMaximumSize(QtCore.QSize(220, 16777215))
        self.frame_3.setStyleSheet("QPushButton{\n"
"font-size: 20px;\n"
"padding: 10px 15px;\n"
"border-radius: 0;\n"
"text-align:  left;\n"
"color: white;\n"
"background-color: rgb(0,0,0,0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(25,50,100);\n"
"}\n"
"QPushButton:focus{\n"
"    background-color: rgb(50, 100, 200);\n"
"color: rgb(0,255,0);\n"
"text-align:  center;\n"
"}\n"
"QFrame{\n"
"background-color: rgb(0, 0, 0, 0.05);\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.hisob_button = QtWidgets.QPushButton(self.frame_3)
        self.hisob_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.hisob_button.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.hisob_button.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/man.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.hisob_button.setIcon(icon1)
        self.hisob_button.setIconSize(QtCore.QSize(40, 40))
        self.hisob_button.setObjectName("hisob_button")
        self.verticalLayout.addWidget(self.hisob_button)
        self.admins_button_2 = QtWidgets.QPushButton(self.frame_3)
        self.admins_button_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.admins_button_2.setStyleSheet("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.admins_button_2.setIcon(icon2)
        self.admins_button_2.setIconSize(QtCore.QSize(40, 40))
        self.admins_button_2.setObjectName("admins_button_2")
        self.verticalLayout.addWidget(self.admins_button_2)
        self.admins_button = QtWidgets.QPushButton(self.frame_3)
        self.admins_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.admins_button.setStyleSheet("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/analysis.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.admins_button.setIcon(icon3)
        self.admins_button.setIconSize(QtCore.QSize(40, 40))
        self.admins_button.setObjectName("admins_button")
        self.verticalLayout.addWidget(self.admins_button)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.frame_3)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setStyleSheet("font-size: 16px;\n"
"padding: 10px;\n"
"border: 3px;\n"
"background: rgb(0,0,255,0.2);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.frame = QtWidgets.QFrame(self.frame_2)
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame)
        self.stackedWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.stackedWidget.setStyleSheet("\n"
"QLineEdit {\n"
"padding: 10px;\n"
"color: cyan;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0.409, stop:0 rgba(255, 241, 0, 55), stop:0.517241 rgba(74, 255, 0, 55), stop:1 rgba(0, 232, 255, 55));\n"
"border-radius: 3px;\n"
"font-size: 24px;\n"
"}\n"
"QLabel{\n"
"color: rgb(127,127,127);\n"
"font-size: 16px;\n"
"}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.account_page = QtWidgets.QWidget()
        self.account_page.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.account_page.setObjectName("account_page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.account_page)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.account_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_2.sizePolicy().hasHeightForWidth())
        self.scrollArea_2.setSizePolicy(sizePolicy)
        self.scrollArea_2.setStyleSheet("")
        self.scrollArea_2.setInputMethodHints(QtCore.Qt.ImhNone)
        self.scrollArea_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(-313, 0, 411, 1589))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_13.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label.setObjectName("label")
        self.verticalLayout_13.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_13.addWidget(self.lineEdit)
        self.line_9 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.verticalLayout_13.addWidget(self.line_9)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_13.addWidget(self.label_3)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_13.addWidget(self.lineEdit_2)
        self.line_10 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.verticalLayout_13.addWidget(self.line_10)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_13.addWidget(self.label_4)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_13.addWidget(self.lineEdit_3)
        self.line_5 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_13.addWidget(self.line_5)
        self.label_36 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_36.setObjectName("label_36")
        self.verticalLayout_13.addWidget(self.label_36)
        self.frame_32 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_32.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_32.setStyleSheet("background-color: rgb(0, 255, 255,  150);\n"
"font-size: 22px;")
        self.frame_32.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_32.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_32.setObjectName("frame_32")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_32)
        self.horizontalLayout_11.setContentsMargins(0, 0, 9, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_32)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        self.pushButton_9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_9.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_9.setStyleSheet("QPushButton{\n"
"font-size: 20px;\n"
"padding: 8px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255,255,255,100);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(255,255,255);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(50, 255, 255);\n"
"color: rgb(0,255,0);\n"
"}")
        self.pushButton_9.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9.setIcon(icon4)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_11.addWidget(self.pushButton_9)
        self.maktab_nomi = QtWidgets.QLabel(self.frame_32)
        self.maktab_nomi.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.maktab_nomi.setAlignment(QtCore.Qt.AlignCenter)
        self.maktab_nomi.setObjectName("maktab_nomi")
        self.horizontalLayout_11.addWidget(self.maktab_nomi)
        self.label_20 = QtWidgets.QLabel(self.frame_32)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setMinimumSize(QtCore.QSize(50, 50))
        self.label_20.setMaximumSize(QtCore.QSize(50, 50))
        self.label_20.setText("")
        self.label_20.setPixmap(QtGui.QPixmap("icons/school.png"))
        self.label_20.setScaledContents(True)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_11.addWidget(self.label_20)
        self.verticalLayout_13.addWidget(self.frame_32)
        self.line_8 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout_13.addWidget(self.line_8)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_13.addWidget(self.label_5)
        self.frame_12 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_12.sizePolicy().hasHeightForWidth())
        self.frame_12.setSizePolicy(sizePolicy)
        self.frame_12.setStyleSheet("font: 75 italic 24pt \"Latin Modern Mono\";")
        self.frame_12.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_9.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.frame_27 = QtWidgets.QFrame(self.frame_12)
        self.frame_27.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(48, 49, 50,127);")
        self.frame_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.frame_27)
        self.verticalLayout_23.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.label_32 = QtWidgets.QLabel(self.frame_27)
        self.label_32.setStyleSheet("padding: 10px 0;\n"
"border-radius: 4px;\n"
"background-color: rgb(0, 0, 0, 130);\n"
"font-size: 16px;")
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_23.addWidget(self.label_32)
        self.frame_28 = QtWidgets.QFrame(self.frame_27)
        self.frame_28.setStyleSheet("background-color: rgb(0, 0, 0, 0);\n"
"color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0.409, stop:0 rgba(0, 255, 0, 0), stop:0.147783 rgba(0, 255, 0, 255), stop:0.448276 rgba(138, 190, 0, 255), stop:0.640394 rgba(219, 134, 104, 255), stop:0.837438 rgba(155, 255, 255, 255), stop:1 rgba(0, 255, 255, 255));")
        self.frame_28.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.frame_28)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.label_33 = QtWidgets.QLabel(self.frame_28)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_33.sizePolicy().hasHeightForWidth())
        self.label_33.setSizePolicy(sizePolicy)
        self.label_33.setText("")
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.verticalLayout_24.addWidget(self.label_33)
        self.verticalLayout_23.addWidget(self.frame_28)
        self.horizontalLayout_9.addWidget(self.frame_27)
        self.frame_25 = QtWidgets.QFrame(self.frame_12)
        self.frame_25.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(48, 49, 50,127);")
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.frame_25)
        self.verticalLayout_21.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_30 = QtWidgets.QLabel(self.frame_25)
        self.label_30.setStyleSheet("padding: 10px 0;\n"
"border-radius: 4px;\n"
"background-color: rgb(0, 0, 0, 130);\n"
"font-size: 16px;")
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_21.addWidget(self.label_30)
        self.frame_26 = QtWidgets.QFrame(self.frame_25)
        self.frame_26.setStyleSheet("background-color: rgb(0, 0, 0, 0);\n"
"color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0.409, stop:0 rgba(0, 255, 0, 0), stop:0.147783 rgba(0, 255, 0, 255), stop:0.448276 rgba(138, 190, 0, 255), stop:0.640394 rgba(219, 134, 104, 255), stop:0.837438 rgba(155, 255, 255, 255), stop:1 rgba(0, 255, 255, 255));")
        self.frame_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.frame_26)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label_31 = QtWidgets.QLabel(self.frame_26)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_31.sizePolicy().hasHeightForWidth())
        self.label_31.setSizePolicy(sizePolicy)
        self.label_31.setText("")
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_22.addWidget(self.label_31)
        self.verticalLayout_21.addWidget(self.frame_26)
        self.horizontalLayout_9.addWidget(self.frame_25)
        self.verticalLayout_13.addWidget(self.frame_12)
        self.line_6 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_13.addWidget(self.line_6)
        self.textBrowser = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser.sizePolicy().hasHeightForWidth())
        self.textBrowser.setSizePolicy(sizePolicy)
        self.textBrowser.setMinimumSize(QtCore.QSize(0, 900))
        self.textBrowser.setStyleSheet("border: 0")
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_13.addWidget(self.textBrowser)
        self.frame_34 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_34.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_34.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_34.setObjectName("frame_34")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_34)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_35 = QtWidgets.QLabel(self.frame_34)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_35.sizePolicy().hasHeightForWidth())
        self.label_35.setSizePolicy(sizePolicy)
        self.label_35.setText("")
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_12.addWidget(self.label_35)
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_34)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_10.sizePolicy().hasHeightForWidth())
        self.pushButton_10.setSizePolicy(sizePolicy)
        self.pushButton_10.setMaximumSize(QtCore.QSize(16777215, 50))
        self.pushButton_10.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_10.setStyleSheet("QPushButton{\n"
"border-radius: 25px;\n"
"padding: 14px;\n"
"font-size: 24px;\n"
"border-top-left-radius:0;\n"
"border-bottom-left-radius:0;\n"
"color: black;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.227, x2:1, y2:0.739, stop:0 rgba(0, 255, 0, 255), stop:0.507389 rgba(0, 255, 255, 255), stop:1 rgba(0, 56, 255, 255));\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 255, 77);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: qlineargradient(spread:pad, x2:0, y2:0.227, x1:1, y1:0.739, stop:0 rgba(0, 255, 0, 255), stop:0.507389 rgba(0, 255, 255, 255), stop:1 rgba(0, 56, 255, 255));\n"
"}")
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_12.addWidget(self.pushButton_10)
        self.label_21 = QtWidgets.QLabel(self.frame_34)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_21.setStyleSheet("\n"
"padding: 10px;\n"
"color: cyan;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0.409, stop:0 rgba(255, 241, 0, 55), stop:0.517241 rgba(74, 255, 0, 55), stop:1 rgba(0, 232, 255, 55));\n"
"border-radius: 3px;\n"
"font-size: 16px;\n"
"border-radius: 25px;\n"
"border-top-right-radius:0;\n"
"border-bottom-right-radius:0;")
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_12.addWidget(self.label_21)
        self.label_17 = QtWidgets.QLabel(self.frame_34)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setStyleSheet("font-size: 20px;\n"
"color: cyan")
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_12.addWidget(self.label_17)
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_34)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        self.pushButton_8.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_8.setStyleSheet("QPushButton{\n"
"font-size: 30px;\n"
"padding: 6px;;\n"
"border-radius: 25px;\n"
"border: 0;\n"
"border-top-left-radius:0;\n"
"border-bottom-left-radius:0;\n"
"background-color: rgb(40,40,40);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(0,0,0,120);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(0,50,0,120);\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_12.addWidget(self.pushButton_8)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame_34)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_5.sizePolicy().hasHeightForWidth())
        self.lineEdit_5.setSizePolicy(sizePolicy)
        self.lineEdit_5.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEdit_5.setMaximumSize(QtCore.QSize(16777215, 50))
        self.lineEdit_5.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_5.setStyleSheet("border-radius: 0")
        self.lineEdit_5.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_12.addWidget(self.lineEdit_5)
        self.pushButton_11 = QtWidgets.QPushButton(self.frame_34)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_11.sizePolicy().hasHeightForWidth())
        self.pushButton_11.setSizePolicy(sizePolicy)
        self.pushButton_11.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_11.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_11.setStyleSheet("QPushButton{\n"
"font-size: 30px;\n"
"padding: 6px;;\n"
"border-radius: 25px;\n"
"border: 0;\n"
"border-top-right-radius:0;\n"
"border-bottom-right-radius:0;\n"
"background-color: rgb(40,40,40);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(0,0,0,120);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(0,50,0,120);\n"
"}")
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_12.addWidget(self.pushButton_11)
        self.label_22 = QtWidgets.QLabel(self.frame_34)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setText("")
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_12.addWidget(self.label_22)
        self.verticalLayout_13.addWidget(self.frame_34)
        self.line_7 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_13.addWidget(self.line_7)
        self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pushButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(80,80,80, 127);\n"
"border-radius: 5px;\n"
"padding: 10px;\n"
"font-size: 16px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(255,0,0,127);\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/logout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon5)
        self.pushButton.setIconSize(QtCore.QSize(40, 40))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_13.addWidget(self.pushButton)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_3.addWidget(self.scrollArea_2)
        self.stackedWidget.addWidget(self.account_page)
        self.home_page = QtWidgets.QWidget()
        self.home_page.setObjectName("home_page")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.home_page)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_10 = QtWidgets.QFrame(self.home_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_10.sizePolicy().hasHeightForWidth())
        self.frame_10.setSizePolicy(sizePolicy)
        self.frame_10.setStyleSheet("font: 75 italic 24pt \"Latin Modern Mono\";")
        self.frame_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_23 = QtWidgets.QFrame(self.frame_10)
        self.frame_23.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(48, 49, 50,127);")
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_23)
        self.verticalLayout_19.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_29 = QtWidgets.QLabel(self.frame_23)
        self.label_29.setStyleSheet("padding: 10px 0;\n"
"border-radius: 4px;\n"
"background-color: rgb(0, 0, 0, 130);\n"
"font-size: 16px;")
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_19.addWidget(self.label_29)
        self.frame_24 = QtWidgets.QFrame(self.frame_23)
        self.frame_24.setStyleSheet("background-color: rgb(0, 0, 0, 0);\n"
"color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0.409, stop:0 rgba(0, 255, 0, 0), stop:0.147783 rgba(0, 255, 0, 255), stop:0.448276 rgba(138, 190, 0, 255), stop:0.640394 rgba(219, 134, 104, 255), stop:0.837438 rgba(155, 255, 255, 255), stop:1 rgba(0, 255, 255, 255));")
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.frame_24)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_27 = QtWidgets.QLabel(self.frame_24)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        self.label_27.setText("")
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_20.addWidget(self.label_27)
        self.verticalLayout_19.addWidget(self.frame_24)
        self.horizontalLayout_7.addWidget(self.frame_23)
        self.frame_21 = QtWidgets.QFrame(self.frame_10)
        self.frame_21.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(48, 49, 50,127);")
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_21)
        self.verticalLayout_17.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_28 = QtWidgets.QLabel(self.frame_21)
        self.label_28.setStyleSheet("padding: 10px 0;\n"
"border-radius: 4px;\n"
"background-color: rgb(0, 0, 0, 130);\n"
"font-size: 16px;")
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_17.addWidget(self.label_28)
        self.frame_22 = QtWidgets.QFrame(self.frame_21)
        self.frame_22.setStyleSheet("background-color: rgb(0, 0, 0, 0);\n"
"color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0.409, stop:0 rgba(0, 255, 0, 0), stop:0.147783 rgba(0, 255, 0, 255), stop:0.448276 rgba(138, 190, 0, 255), stop:0.640394 rgba(219, 134, 104, 255), stop:0.837438 rgba(155, 255, 255, 255), stop:1 rgba(0, 255, 255, 255));")
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_22)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_26 = QtWidgets.QLabel(self.frame_22)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        self.label_26.setText("")
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_18.addWidget(self.label_26)
        self.verticalLayout_17.addWidget(self.frame_22)
        self.horizontalLayout_7.addWidget(self.frame_21)
        self.verticalLayout_7.addWidget(self.frame_10)
        self.pushButton_6 = QtWidgets.QPushButton(self.home_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 0, 0, 0);\n"
"border-radius: 0px;\n"
"font-size: 20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(0, 0, 50, 50);\n"
"}\n"
"")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon6)
        self.pushButton_6.setIconSize(QtCore.QSize(100, 100))
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_7.addWidget(self.pushButton_6)
        self.frame_11 = QtWidgets.QFrame(self.home_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_11.sizePolicy().hasHeightForWidth())
        self.frame_11.setSizePolicy(sizePolicy)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame_13 = QtWidgets.QFrame(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(self.frame_13.sizePolicy().hasHeightForWidth())
        self.frame_13.setSizePolicy(sizePolicy)
        self.frame_13.setStyleSheet("border-radius: 10px;\n"
"font-size: 24px;\n"
"background-color: rgb(48, 49, 49);")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_8.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_17 = QtWidgets.QFrame(self.frame_13)
        self.frame_17.setStyleSheet("background-color: rgb(0, 0, 0, 0);\n"
"color: black;")
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_17)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_14 = QtWidgets.QLabel(self.frame_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.verticalLayout_10.addWidget(self.label_14)
        self.label_15 = QtWidgets.QLabel(self.frame_17)
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.verticalLayout_10.addWidget(self.label_15)
        self.verticalLayout_8.addWidget(self.frame_17)
        self.label_12 = QtWidgets.QLabel(self.frame_13)
        self.label_12.setStyleSheet("padding: 10px 0;\n"
"border-radius: 4px;\n"
"background-color: rgb(0, 0, 0, 130);")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_8.addWidget(self.label_12)
        self.horizontalLayout_8.addWidget(self.frame_13)
        self.frame_4 = QtWidgets.QFrame(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(9)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_11.setContentsMargins(0, 2, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_15 = QtWidgets.QFrame(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_15.sizePolicy().hasHeightForWidth())
        self.frame_15.setSizePolicy(sizePolicy)
        self.frame_15.setMinimumSize(QtCore.QSize(0, 1))
        self.frame_15.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_11.addWidget(self.frame_15)
        self.frame_16 = QtWidgets.QFrame(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.frame_16.sizePolicy().hasHeightForWidth())
        self.frame_16.setSizePolicy(sizePolicy)
        self.frame_16.setMinimumSize(QtCore.QSize(0, 10))
        self.frame_16.setStyleSheet("border-radius: 10px;\n"
"font-size: 20px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0.409, stop:0 rgba(255, 241, 0), stop:0.517241 rgba(74, 255, 0), stop:1 rgba(0, 232, 255));")
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_15.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.frame_18 = QtWidgets.QFrame(self.frame_16)
        self.frame_18.setStyleSheet("background-color: rgb(0, 0, 0, 0);\n"
"color: black;")
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_18)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_23 = QtWidgets.QLabel(self.frame_18)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setText("")
        self.label_23.setObjectName("label_23")
        self.verticalLayout_16.addWidget(self.label_23)
        self.label_24 = QtWidgets.QLabel(self.frame_18)
        self.label_24.setText("")
        self.label_24.setObjectName("label_24")
        self.verticalLayout_16.addWidget(self.label_24)
        self.verticalLayout_15.addWidget(self.frame_18)
        self.label_25 = QtWidgets.QLabel(self.frame_16)
        self.label_25.setStyleSheet("padding: 10px 0;\n"
"border-radius: 4px;\n"
"background-color: rgb(0, 0, 0, 130);")
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_15.addWidget(self.label_25)
        self.verticalLayout_11.addWidget(self.frame_16)
        self.frame_20 = QtWidgets.QFrame(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_20.sizePolicy().hasHeightForWidth())
        self.frame_20.setSizePolicy(sizePolicy)
        self.frame_20.setMinimumSize(QtCore.QSize(0, 1))
        self.frame_20.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.verticalLayout_11.addWidget(self.frame_20)
        self.horizontalLayout_8.addWidget(self.frame_4)
        self.frame_29 = QtWidgets.QFrame(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_29.sizePolicy().hasHeightForWidth())
        self.frame_29.setSizePolicy(sizePolicy)
        self.frame_29.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.frame_29)
        self.verticalLayout_25.setContentsMargins(0, 2, 0, 0)
        self.verticalLayout_25.setSpacing(0)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.label_34 = QtWidgets.QLabel(self.frame_29)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.label_34.sizePolicy().hasHeightForWidth())
        self.label_34.setSizePolicy(sizePolicy)
        self.label_34.setText("")
        self.label_34.setObjectName("label_34")
        self.verticalLayout_25.addWidget(self.label_34)
        self.frame_14 = QtWidgets.QFrame(self.frame_29)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.frame_14.sizePolicy().hasHeightForWidth())
        self.frame_14.setSizePolicy(sizePolicy)
        self.frame_14.setStyleSheet("border-radius: 10px;\n"
"font-size: 18px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0.409, stop:0 rgba(255, 15, 0, 255), stop:0.517241 rgba(226, 136, 5, 255), stop:1 rgba(255, 114, 0, 255));")
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_9.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_19 = QtWidgets.QFrame(self.frame_14)
        self.frame_19.setStyleSheet("background-color: rgb(0, 0, 0, 0);\n"
"color: black;")
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_19)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_18 = QtWidgets.QLabel(self.frame_19)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.verticalLayout_12.addWidget(self.label_18)
        self.label_19 = QtWidgets.QLabel(self.frame_19)
        self.label_19.setText("")
        self.label_19.setObjectName("label_19")
        self.verticalLayout_12.addWidget(self.label_19)
        self.verticalLayout_9.addWidget(self.frame_19)
        self.label_13 = QtWidgets.QLabel(self.frame_14)
        self.label_13.setStyleSheet("padding: 8px 0;\n"
"border-radius: 4px;\n"
"background-color: rgb(0, 0, 0, 130);")
        self.label_13.setText("")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_9.addWidget(self.label_13)
        self.verticalLayout_25.addWidget(self.frame_14)
        self.label_38 = QtWidgets.QLabel(self.frame_29)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.label_38.sizePolicy().hasHeightForWidth())
        self.label_38.setSizePolicy(sizePolicy)
        self.label_38.setText("")
        self.label_38.setObjectName("label_38")
        self.verticalLayout_25.addWidget(self.label_38)
        self.horizontalLayout_8.addWidget(self.frame_29)
        self.frame_33 = QtWidgets.QFrame(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_33.sizePolicy().hasHeightForWidth())
        self.frame_33.setSizePolicy(sizePolicy)
        self.frame_33.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_33.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_33.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_33.setObjectName("frame_33")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.frame_33)
        self.verticalLayout_28.setContentsMargins(0, 2, 0, 0)
        self.verticalLayout_28.setSpacing(0)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.label_43 = QtWidgets.QLabel(self.frame_33)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.label_43.sizePolicy().hasHeightForWidth())
        self.label_43.setSizePolicy(sizePolicy)
        self.label_43.setText("")
        self.label_43.setObjectName("label_43")
        self.verticalLayout_28.addWidget(self.label_43)
        self.frame_36 = QtWidgets.QFrame(self.frame_33)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.frame_36.sizePolicy().hasHeightForWidth())
        self.frame_36.setSizePolicy(sizePolicy)
        self.frame_36.setStyleSheet("font-size: 14px;\n"
"border-radius: 10px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0.409, stop:0 rgba(255, 15, 0, 255), stop:0.517241 rgba(226, 136, 5, 255), stop:1 rgba(255, 114, 0, 255));")
        self.frame_36.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_36.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_36.setObjectName("frame_36")
        self.verticalLayout_33 = QtWidgets.QVBoxLayout(self.frame_36)
        self.verticalLayout_33.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.frame_38 = QtWidgets.QFrame(self.frame_36)
        self.frame_38.setStyleSheet("background-color: rgb(0, 0, 0, 0);\n"
"color: black;")
        self.frame_38.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_38.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_38.setObjectName("frame_38")
        self.verticalLayout_38 = QtWidgets.QVBoxLayout(self.frame_38)
        self.verticalLayout_38.setObjectName("verticalLayout_38")
        self.label_48 = QtWidgets.QLabel(self.frame_38)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_48.sizePolicy().hasHeightForWidth())
        self.label_48.setSizePolicy(sizePolicy)
        self.label_48.setText("")
        self.label_48.setObjectName("label_48")
        self.verticalLayout_38.addWidget(self.label_48)
        self.label_49 = QtWidgets.QLabel(self.frame_38)
        self.label_49.setText("")
        self.label_49.setObjectName("label_49")
        self.verticalLayout_38.addWidget(self.label_49)
        self.verticalLayout_33.addWidget(self.frame_38)
        self.label_50 = QtWidgets.QLabel(self.frame_36)
        self.label_50.setStyleSheet("padding:6px 0;\n"
"border-radius: 4px;\n"
"background-color: rgb(0, 0, 0, 130);")
        self.label_50.setText("")
        self.label_50.setAlignment(QtCore.Qt.AlignCenter)
        self.label_50.setObjectName("label_50")
        self.verticalLayout_33.addWidget(self.label_50)
        self.verticalLayout_28.addWidget(self.frame_36)
        self.label_39 = QtWidgets.QLabel(self.frame_33)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.label_39.sizePolicy().hasHeightForWidth())
        self.label_39.setSizePolicy(sizePolicy)
        self.label_39.setText("")
        self.label_39.setObjectName("label_39")
        self.verticalLayout_28.addWidget(self.label_39)
        self.horizontalLayout_8.addWidget(self.frame_33)
        self.verticalLayout_7.addWidget(self.frame_11)
        self.stackedWidget.addWidget(self.home_page)
        self.data_page = QtWidgets.QWidget()
        self.data_page.setObjectName("data_page")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.data_page)
        self.verticalLayout_4.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_5 = QtWidgets.QFrame(self.data_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setStyleSheet("QComboBox{\n"
"padding: 10px;\n"
"color: rgb(0,0,80);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0.409, stop:0 rgba(255, 241, 0, 255), stop:0.517241 rgba(74, 255, 0, 255), stop:1 rgba(0, 232, 255, 255));\n"
"border-radius: 3px;\n"
"font-size: 20px;\n"
"}\n"
"QComboBox QFrame{\n"
"    background-color: qradialgradient(spread:pad, cx:0, cy:0.506, radius:1.004, fx:0, fy:0.506, stop:0 rgba(255, 124, 0, 255), stop:0.233422 rgba(255, 125, 0, 255), stop:0.38992 rgba(255, 127, 0, 234), stop:1 rgba(0, 255, 0, 0));\n"
"font-size: 18px;\n"
"color: black;\n"
"padding: 2px;\n"
"}\n"
"QLineEdit {\n"
"padding: 8px;\n"
"color: none;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0.409, stop:0 rgba(255, 241, 0, 55), stop:0.517241 rgba(74, 255, 0, 55), stop:1 rgba(0, 232, 255, 55));\n"
"border-radius: 3px;\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"border-radius: 10px;\n"
"padding: 10px;\n"
"font-size: 20px;\n"
"color: black;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.227, x2:1, y2:0.739, stop:0 rgba(0, 255, 0, 255), stop:0.507389 rgba(0, 255, 255, 255), stop:1 rgba(0, 56, 255, 255));\n"
"border: 2px solid rgb(0,0,0,0);\n"
"}\n"
"QPushButton:hover{\n"
"border-color:  black;\n"
"    background-color: rgb(0, 255, 77);\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 1, 11, 1, 1)
        self.frame_7 = QtWidgets.QFrame(self.frame_5)
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.gridLayout.addWidget(self.frame_7, 1, 12, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_4.setMinimumSize(QtCore.QSize(100, 0))
        self.lineEdit_4.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lineEdit_4.setStyleSheet("color: white;")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 1, 6, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.frame_5)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 6, 1, 1)
        self.line = QtWidgets.QFrame(self.frame_5)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 0, 3, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.frame_5)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 1, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame_5)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.frame_5)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 4, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_2.sizePolicy().hasHeightForWidth())
        self.comboBox_2.setSizePolicy(sizePolicy)
        self.comboBox_2.setMinimumSize(QtCore.QSize(150, 0))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.gridLayout.addWidget(self.comboBox_2, 1, 4, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setMinimumSize(QtCore.QSize(150, 0))
        self.comboBox.setDuplicatesEnabled(False)
        self.comboBox.setFrame(True)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 1, 2, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.frame_5)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 0, 5, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.frame_5)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 1, 5, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_3.sizePolicy().hasHeightForWidth())
        self.comboBox_3.setSizePolicy(sizePolicy)
        self.comboBox_3.setMinimumSize(QtCore.QSize(150, 0))
        self.comboBox_3.setDuplicatesEnabled(False)
        self.comboBox_3.setFrame(True)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.gridLayout.addWidget(self.comboBox_3, 1, 0, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.frame_5)
        self.label_37.setAlignment(QtCore.Qt.AlignCenter)
        self.label_37.setObjectName("label_37")
        self.gridLayout.addWidget(self.label_37, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.frame_5)
        self.label_7 = QtWidgets.QLabel(self.data_page)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_4.addWidget(self.label_7)
        self.scrollArea = QtWidgets.QScrollArea(self.data_page)
        self.scrollArea.setFocusPolicy(QtCore.Qt.NoFocus)
        self.scrollArea.setStyleSheet("font-size: 18px;")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 962, 475))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_6 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_8 = QtWidgets.QFrame(self.frame_6)
        self.frame_8.setStyleSheet("QFrame{\n"
"padding: 8px;\n"
"}\n"
"QFrame:hover{\n"
"    background-color: rgb(40, 40, 40,140);\n"
"}")
        self.frame_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"border-radius: 5px;\n"
"padding: 10px\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(20, 100, 100);\n"
"color: rgb(0,255,0);\n"
"}")
        self.pushButton_4.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icons/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon7)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_4.addWidget(self.pushButton_4)
        self.label_75 = QtWidgets.QLabel(self.frame_8)
        self.label_75.setStyleSheet("background-color: rgb(0, 0, 0, 0);\n"
"color: rgb(180,180,255);")
        self.label_75.setObjectName("label_75")
        self.horizontalLayout_4.addWidget(self.label_75)
        self.label_8 = QtWidgets.QLabel(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setStyleSheet("background-color: none;\n"
"color: rgb(0,255,0);")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"font-size: 20px;\n"
"padding: 8px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255,255,255,100);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(255,255,255);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(50, 255, 255);\n"
"color: rgb(0,255,0);\n"
"}")
        self.pushButton_2.setText("")
        self.pushButton_2.setIcon(icon4)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_4.addWidget(self.pushButton_2)
        self.verticalLayout_6.addWidget(self.frame_8)
        self.verticalLayout_5.addWidget(self.frame_6)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_4.addWidget(self.scrollArea)
        self.pages_frame = QtWidgets.QFrame(self.data_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pages_frame.sizePolicy().hasHeightForWidth())
        self.pages_frame.setSizePolicy(sizePolicy)
        self.pages_frame.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 0, 0, 0);\n"
"border-radius: 0;\n"
"padding: 10px;\n"
"font-size: 16px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(40, 40, 40);\n"
"color: white;\n"
"}")
        self.pages_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.pages_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pages_frame.setObjectName("pages_frame")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.pages_frame)
        self.horizontalLayout_19.setContentsMargins(0, 4, 0, 0)
        self.horizontalLayout_19.setSpacing(0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_6 = QtWidgets.QLabel(self.pages_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_19.addWidget(self.label_6)
        self.p1 = QtWidgets.QPushButton(self.pages_frame)
        self.p1.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.p1.setObjectName("p1")
        self.horizontalLayout_19.addWidget(self.p1)
        self.p2 = QtWidgets.QPushButton(self.pages_frame)
        self.p2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.p2.setObjectName("p2")
        self.horizontalLayout_19.addWidget(self.p2)
        self.p3 = QtWidgets.QPushButton(self.pages_frame)
        self.p3.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.p3.setObjectName("p3")
        self.horizontalLayout_19.addWidget(self.p3)
        self.p4 = QtWidgets.QPushButton(self.pages_frame)
        self.p4.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.p4.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.227, x2:1, y2:0.739, stop:0 rgba(0, 255, 0, 255), stop:0.507389 rgba(0, 255, 255, 255), stop:1 rgba(0, 56, 255, 255));\n"
"color: black")
        self.p4.setObjectName("p4")
        self.horizontalLayout_19.addWidget(self.p4)
        self.p5 = QtWidgets.QPushButton(self.pages_frame)
        self.p5.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.p5.setObjectName("p5")
        self.horizontalLayout_19.addWidget(self.p5)
        self.p6 = QtWidgets.QPushButton(self.pages_frame)
        self.p6.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.p6.setObjectName("p6")
        self.horizontalLayout_19.addWidget(self.p6)
        self.p7 = QtWidgets.QPushButton(self.pages_frame)
        self.p7.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.p7.setObjectName("p7")
        self.horizontalLayout_19.addWidget(self.p7)
        self.label_72 = QtWidgets.QLabel(self.pages_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_72.sizePolicy().hasHeightForWidth())
        self.label_72.setSizePolicy(sizePolicy)
        self.label_72.setObjectName("label_72")
        self.horizontalLayout_19.addWidget(self.label_72)
        self.page_number_label = QtWidgets.QLabel(self.pages_frame)
        self.page_number_label.setStyleSheet("color: rgba(0, 0, 0, 0);")
        self.page_number_label.setObjectName("page_number_label")
        self.horizontalLayout_19.addWidget(self.page_number_label)
        self.verticalLayout_4.addWidget(self.pages_frame)
        self.label_16 = QtWidgets.QLabel(self.data_page)
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.verticalLayout_4.addWidget(self.label_16)
        self.frame_31 = QtWidgets.QFrame(self.data_page)
        self.frame_31.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_31.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_31.setObjectName("frame_31")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_31)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pushButton_16 = QtWidgets.QPushButton(self.frame_31)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_16.sizePolicy().hasHeightForWidth())
        self.pushButton_16.setSizePolicy(sizePolicy)
        self.pushButton_16.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_16.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_16.setStyleSheet("QPushButton{\n"
"border-radius: 10px;\n"
"padding: 10px;\n"
"font-size: 16px;\n"
"color: cyan;\n"
"border: 2px solid rgb(0,0,0,0);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(40,40,60);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.227, x2:1, y2:0.739, stop:0 rgba(0, 255, 0, 255), stop:0.507389 rgba(0, 255, 255, 255), stop:1 rgba(0, 56, 255, 255));\n"
"border-color:  black;\n"
"color: black;\n"
"}")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("icons/excel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_16.setIcon(icon8)
        self.pushButton_16.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_16.setObjectName("pushButton_16")
        self.horizontalLayout_10.addWidget(self.pushButton_16)
        self.pushButton_15 = QtWidgets.QPushButton(self.frame_31)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_15.sizePolicy().hasHeightForWidth())
        self.pushButton_15.setSizePolicy(sizePolicy)
        self.pushButton_15.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_15.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_15.setStyleSheet("QPushButton{\n"
"border-radius: 10px;\n"
"padding: 10px;\n"
"font-size: 16px;\n"
"color: cyan;\n"
"border: 2px solid rgb(0,0,0,0);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(40,40,60);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.227, x2:1, y2:0.739, stop:0 rgba(0, 255, 0, 255), stop:0.507389 rgba(0, 255, 255, 255), stop:1 rgba(0, 56, 255, 255));\n"
"border-color:  black;\n"
"color: black;\n"
"}")
        self.pushButton_15.setIcon(icon7)
        self.pushButton_15.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_15.setObjectName("pushButton_15")
        self.horizontalLayout_10.addWidget(self.pushButton_15)
        self.pushButton_17 = QtWidgets.QPushButton(self.frame_31)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_17.sizePolicy().hasHeightForWidth())
        self.pushButton_17.setSizePolicy(sizePolicy)
        self.pushButton_17.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_17.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_17.setStyleSheet("QPushButton{\n"
"border-radius: 10px;\n"
"padding: 10px;\n"
"font-size: 16px;\n"
"color: cyan;\n"
"border: 2px solid rgb(0,0,0,0);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(40,40,60);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.227, x2:1, y2:0.739, stop:0 rgba(0, 255, 0, 255), stop:0.507389 rgba(0, 255, 255, 255), stop:1 rgba(0, 56, 255, 255));\n"
"border-color:  black;\n"
"color: black;\n"
"}")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("icons/webenter.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_17.setIcon(icon9)
        self.pushButton_17.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_17.setObjectName("pushButton_17")
        self.horizontalLayout_10.addWidget(self.pushButton_17)
        self.verticalLayout_4.addWidget(self.frame_31)
        self.frame_9 = QtWidgets.QFrame(self.data_page)
        self.frame_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_4.addWidget(self.frame_9)
        self.stackedWidget.addWidget(self.data_page)
        self.horizontalLayout_2.addWidget(self.stackedWidget)
        self.verticalLayout_2.addWidget(self.frame)
        self.horizontalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "KundalikCOM auto login"))
        self.hisob_button.setText(_translate("MainWindow", "Hisob"))
        self.admins_button_2.setText(_translate("MainWindow", "Bosh sahifa"))
        self.admins_button.setText(_translate("MainWindow", "Ma\'lumotlar"))
        self.label_2.setText(_translate("MainWindow", "ProjectsPlatform.uz"))
        self.label.setText(_translate("MainWindow", "Ism va familiya"))
        self.lineEdit.setText(_translate("MainWindow", "Fullname"))
        self.label_3.setText(_translate("MainWindow", "Username"))
        self.lineEdit_2.setText(_translate("MainWindow", "@Username"))
        self.label_4.setText(_translate("MainWindow", "Balance"))
        self.lineEdit_3.setText(_translate("MainWindow", "0 so\'m"))
        self.label_36.setText(_translate("MainWindow", "Maktab ma\'lumotlari"))
        self.maktab_nomi.setText(_translate("MainWindow", "maktab nomi"))
        self.label_5.setText(_translate("MainWindow", "Letsenziya"))
        self.label_32.setText(_translate("MainWindow", "Letsenziya tugash vaqti"))
        self.label_30.setText(_translate("MainWindow", "Letsenziya davomiyligi"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Mongolian Baiti\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Oxygen,Ubuntu,Cantarell,Fira Sans,Droid Sans,Helvetica Neue,sans-serif\'; font-size:20pt; font-weight:600; color:#00ff00;\">________________________________________________________________</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Oxygen,Ubuntu,Cantarell,Fira Sans,Droid Sans,Helvetica Neue,sans-serif\'; font-size:26pt; font-weight:600; color:#00ff00;\">🎁 Bonus</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Oxygen,Ubuntu,Cantarell,Fira Sans,Droid Sans,Helvetica Neue,sans-serif\'; font-size:26pt; font-weight:600; color:rgba(100,255,255,0.8);\">Ulashing va bepul letsenziyaga ega bo\'ling</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Oxygen,Ubuntu,Cantarell,Fira Sans,Droid Sans,Helvetica Neue,sans-serif\'; font-size:22pt; font-weight:600; color:#ffffff;\">Ushbu xizmatimizni boshqalarga ulashing va xizmatimizni har bir sotib olgan foydalanuvchi uchun </span><span style=\" font-family:\'-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Oxygen,Ubuntu,Cantarell,Fira Sans,Droid Sans,Helvetica Neue,sans-serif\'; font-size:22pt; font-weight:600; color:#00ff00;\">1 oylik</span><span style=\" font-family:\'-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Oxygen,Ubuntu,Cantarell,Fira Sans,Droid Sans,Helvetica Neue,sans-serif\'; font-size:22pt; font-weight:600; color:#ffffff;\"> bepul letsenziyani qo\'lga kiriting!</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Oxygen,Ubuntu,Cantarell,Fira Sans,Droid Sans,Helvetica Neue,sans-serif\'; font-size:22pt; color:#00ffff; background-color:#333333;\"> Havola: </span><a name=\"text-to-copy\"></a><span style=\" font-family:\'-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Oxygen,Ubuntu,Cantarell,Fira Sans,Droid Sans,Helvetica Neue,sans-serif\'; font-size:22pt; color:#0000ff;\"> </span><span style=\" font-family:\'-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Oxygen,Ubuntu,Cantarell,Fira Sans,Droid Sans,Helvetica Neue,sans-serif\'; font-size:22pt; color:#0000ff;\"> https://projectsplatform.uz/register?ref=</span><span style=\" font-family:\'-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Oxygen,Ubuntu,Cantarell,Fira Sans,Droid Sans,Helvetica Neue,sans-serif\'; font-size:22pt; color:rgba(100,255,255,0.8);\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Oxygen,Ubuntu,Cantarell,Fira Sans,Droid Sans,Helvetica Neue,sans-serif\'; font-size:22pt; font-weight:600; color:#00ff00;\">Hoziroq ushbu referal havolangizdan nusxa olib telegram orqali ulashing</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Oxygen,Ubuntu,Cantarell,Fira Sans,Droid Sans,Helvetica Neue,sans-serif\'; font-size:20pt; font-weight:600; color:#00ff00;\">________________________________________________________________</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:24pt; font-weight:600; color:#ffd500;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt; font-weight:600; color:#ffd500;\">KundalikCOM</span><span style=\" font-size:24pt; font-weight:600;\"> </span><span style=\" font-size:24pt; font-weight:600; color:#00ffff;\">Desktop</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt; font-weight:600;\">-) O\'quvchi va Ota onalar </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-style:italic; color:#6c6c6c;\">  Barcha eMaktab.uz dagi hisoblarni boshqarish imkoniyati</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt; font-weight:600;\">-) Maktab reytingini oshirish</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt; font-weight:600;\">-) Login parollarni online kiritish</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-style:italic; color:#6c6c6c;\">  o\'quvchilardan login va parollarini bitta bitta yozib olmasdan bitta elon orqali elekron tarzda login parollarni yig\'ish eko tizimi.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:24pt; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt;\">Bir oylik letsenziya: </span><span style=\" font-size:20pt; font-weight:600; color:#ff8000;\">150 000</span><span style=\" font-size:20pt;\"> </span><span style=\" font-size:20pt; color:#0189ff;\">so\'m</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt;\">3 oy yoki undan ko\'proq harid qilinsa </span><span style=\" font-size:20pt; font-weight:600; color:#ff0000;\">-20%</span><span style=\" font-size:20pt;\"> chegirma bilan bir oy uchun: </span><span style=\" font-size:20pt; font-weight:600; color:#00ff00;\">120 000</span><span style=\" font-size:20pt;\"> </span><span style=\" font-size:20pt; color:#0073ff;\">so\'m</span><span style=\" font-size:20pt;\">dan narxlanadi<br />Har </span><span style=\" font-size:20pt; color:#0000ff;\">9</span><span style=\" font-size:20pt;\"> oy olinsa </span><span style=\" font-size:20pt; font-weight:600; color:#00ff26;\">+3</span><span style=\" font-size:20pt;\"> oy bonusga beriladi</span></p></body></html>"))
        self.pushButton_10.setText(_translate("MainWindow", "Sotib olish"))
        self.label_21.setText(_translate("MainWindow", "0 so\'m"))
        self.label_17.setText(_translate("MainWindow", " oy"))
        self.pushButton_8.setText(_translate("MainWindow", "+"))
        self.lineEdit_5.setPlaceholderText(_translate("MainWindow", "0"))
        self.pushButton_11.setText(_translate("MainWindow", "-"))
        self.pushButton.setText(_translate("MainWindow", "Hisobdan chiqish"))
        self.label_29.setText(_translate("MainWindow", "Letsenziya davomiyligi"))
        self.label_28.setText(_translate("MainWindow", "Letsenziya tugash vaqti"))
        self.pushButton_6.setText(_translate("MainWindow", "BARCHA AKKOUNTLARNI\n"
"LOGIN QILIB CHIQISH"))
        self.label_12.setText(_translate("MainWindow", "B U G U N"))
        self.label_25.setText(_translate("MainWindow", "K E CH A"))
        self.pushButton_3.setText(_translate("MainWindow", "Qidirish"))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "Qidirish..."))
        self.label_11.setText(_translate("MainWindow", "O\'quvchi va Ota Onalar"))
        self.label_9.setText(_translate("MainWindow", "Sinf darajalari"))
        self.label_10.setText(_translate("MainWindow", "Sinflar"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Hammasi"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Hammasi"))
        self.comboBox.setItemText(1, _translate("MainWindow", "1"))
        self.comboBox.setItemText(2, _translate("MainWindow", "2"))
        self.comboBox.setItemText(3, _translate("MainWindow", "3"))
        self.comboBox.setItemText(4, _translate("MainWindow", "4"))
        self.comboBox.setItemText(5, _translate("MainWindow", "5"))
        self.comboBox.setItemText(6, _translate("MainWindow", "6"))
        self.comboBox.setItemText(7, _translate("MainWindow", "7"))
        self.comboBox.setItemText(8, _translate("MainWindow", "8"))
        self.comboBox.setItemText(9, _translate("MainWindow", "9"))
        self.comboBox.setItemText(10, _translate("MainWindow", "10"))
        self.comboBox.setItemText(11, _translate("MainWindow", "11"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "O\'quvchilar"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "Ota onalar"))
        self.label_37.setText(_translate("MainWindow", "Filter"))
        self.label_7.setText(_translate("MainWindow", "Jami: 20ta"))
        self.label_75.setText(_translate("MainWindow", "Boynazarov Bexruz Xayrulla o\'g\'li"))
        self.label_8.setText(_translate("MainWindow", "Parol kiritilgan"))
        self.label_6.setText(_translate("MainWindow", "   ...   "))
        self.p1.setText(_translate("MainWindow", "2"))
        self.p2.setText(_translate("MainWindow", "3"))
        self.p3.setText(_translate("MainWindow", "4"))
        self.p4.setText(_translate("MainWindow", "5"))
        self.p5.setText(_translate("MainWindow", "6"))
        self.p6.setText(_translate("MainWindow", "7"))
        self.p7.setText(_translate("MainWindow", "8"))
        self.label_72.setText(_translate("MainWindow", "   ...   "))
        self.page_number_label.setText(_translate("MainWindow", "1"))
        self.pushButton_16.setText(_translate("MainWindow", "Parol kiritilmagan yoki xato\n"
"hisoblar ruyxatini ko\'rish"))
        self.pushButton_15.setText(_translate("MainWindow", "Barcha ma\'lumotlarni\n"
"qayta yuklash"))
        self.pushButton_17.setText(_translate("MainWindow", "Login parollarni\n"
"online kiritish"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
